version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lime8
      MONGO_INITDB_ROOT_PASSWORD: lime8
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
