@baseUrl = http://localhost:4080
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true
{
  "username": "your_username",
  "password": "your_password",
  "email": "your_email@example.com",
  "avatarColor": "your_avatar_color",
  "avatarImage": "your_avatar_image"
}
